import 'package:flutter/material.dart';
import 'core/theme/app_theme.dart';
import 'core/network/api_client.dart';

void main() => runApp(const AgriSmartApp());
class AgriSmartApp extends StatelessWidget { const AgriSmartApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(title:'AgriSmart',debugShowCheckedModeBanner:false,theme:AppTheme.light(),home:const DashboardPage()); }
class DashboardPage extends StatefulWidget { const DashboardPage({super.key}); @override State<DashboardPage> createState()=>_DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage> { bool loading=false; String message='Welcome to AgriSmart'; final api=ApiClient();
Future<void> loadDashboard() async { setState(()=>loading=true); try { final r=await api.get('/dashboard'); setState(()=>message=r['message']?.toString() ?? 'Dashboard ready'); } catch(e) { setState(()=>message='Connect the AgriSmart API to load your dashboard.'); } finally { if(mounted)setState(()=>loading=false); } }
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('AgriSmart'),actions:[IconButton(onPressed:loadDashboard,icon:const Icon(Icons.refresh))]),body:SafeArea(child:ListView(padding:const EdgeInsets.all(AppSpacing.md),children:[Text('AI-Powered Smart Farming Assistant',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:AppSpacing.lg),Text(message,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:AppSpacing.lg),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,children:const [FeatureCard(icon:Icons.grass,title:'Crop Recommendation'),FeatureCard(icon:Icons.local_florist,title:'Disease Detection'),FeatureCard(icon:Icons.analytics,title:'Yield Prediction'),FeatureCard(icon:Icons.smart_toy,title:'AgriBot'),FeatureCard(icon:Icons.cloud,title:'Weather'),FeatureCard(icon:Icons.agriculture,title:'Farm Decisions')]),if(loading)const Padding(padding:EdgeInsets.only(top:24),child:Center(child:CircularProgressIndicator()))])); }
}
class FeatureCard extends StatelessWidget { const FeatureCard({super.key,required this.icon,required this.title}); final IconData icon; final String title; @override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(AppSpacing.md),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:34,color:AppColors.primary),const SizedBox(height:8),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w600))]))); }
